import React from "react";
import lodash from "lodash";

const Hello = () => {
  return (
    <div>
      {lodash.add(1, 2)}
      MHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHello
    </div>
  );
};

export default Hello;
